plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lyalnr.torchlight'
    compileSdk 34

    defaultConfig {
        applicationId "com.lyalnr.torchlight"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 无任何 androidx 依赖，避免 kotlin-stdlib 版本冲突
}